// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzpsmtooijbygxouibsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cHNtdG9vaWpieWd4b3VpYnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzU0MjksImV4cCI6MjA2ODkxMTQyOX0.fMFobzYyNqG9ayljFur5urSlLde11Tygt_gENd6kpo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});